## CI - Player And Plugin Tests
name: Player And Plugin Tests
run-name: Player And Plugin Tests

permissions:
  id-token: write
  contents: read
  packages: read
  actions: read
  pull-requests: read
  issues: write

on:
  pull_request:
    branches:
      - "*"

jobs:
  tests:
    uses: kaltura/playkit-js-common/.github/workflows/cypress.yml@jfrog-migration-test
    secrets: inherit
  build:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_tests.yaml@jfrog-migration-test
    with:
      node-version: '24.x'
      npm-run-to-execute: 'build'
  lint:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_tests.yaml@jfrog-migration-test
    with:
      node-version: '24.x'
      npm-run-to-execute: 'lint'



  notification:
    if: always()
    uses: kaltura/ovp-pipelines-pub/.github/workflows/notification.yaml@jfrog-migration-test
    needs: tests
    secrets:
      PLAYER_MSTEAMS_WEBHOOK: ${{ secrets.PLAYER_MSTEAMS_WEBHOOK }}
    with:
      failure-status: ${{ contains(needs.*.result, 'failure') }}
      cancelled-status: ${{ contains(needs.*.result, 'cancelled') }}
      is-test: 'true'